name: Run tests
on:
    push:
      branches:
        - main
  
  jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm run test
